services:
    other_examples.payum.action.capture_cart_with_paypal_express_checkout:
        class: Acme\OtherExamplesBundle\Payum\Action\CaptureCartWithPaypalExpressCheckoutAction
        arguments:
            - @payum
            - @payum.security.token_factory
        tags:
            - { name: payum.action, gateway: paypal_express_checkout_and_doctrine_orm, alias: foo }
            
    other_examples.payum.action.capture_cart_with_authorize_net:
        class: Acme\OtherExamplesBundle\Payum\Action\CaptureCartWithAuthorizeNetAction
        arguments:
            - @service_container
            
    other_examples.payum.action.status_details_aggregated_null_model:
        class: Acme\OtherExamplesBundle\Payum\Action\StatusDetailsAggregatedNullModelAction